return {
  -- -- Virker ikke :/
  -- "vigoux/ltex-ls.nvim",
  -- enable = false,
  -- opts = {
  --   on_attach = on_attach,
  --   capabilities = capabilities,
  --   use_spellfile = false,
  --   filetypes = { "tex", "latex", "bib" },
  --
  --   settings = {
  --     ltex = {
  --       -- language = "da_DK",
  --       language = "auto",
  --       additionalRules = {
  --         enablePickyRules = true,
  --         motherTongue = "da_DK",
  --       },
  --       dictionary = (function()
  --         -- For dictionary, search for files in the runtime to have
  --         -- and include them as externals the format for them is
  --         -- dict/{LANG}.txt
  --         --
  --         -- Also add dict/default.txt to all of them
  --         local files = {}
  --         for _, file in ipairs(vim.api.nvim_get_runtime_file("dict/*", true)) do
  --           local lang = vim.fn.fnamemodify(file, ":t:r")
  --           local fullpath = vim.fs.normalize(file, ":p")
  --           files[lang] = { ":" .. fullpath }
  --         end
  --
  --         if files.default then
  --           for lang, _ in pairs(files) do
  --             if lang ~= "default" then
  --               vim.list_extend(files[lang], files.default)
  --             end
  --           end
  --           files.default = nil
  --         end
  --         return files
  --       end)(),
  --     },
  --   },
  -- },
}
