[main]
font = 0xProto Nerd Font:size=12
pad = 10x10

[key-bindings]
scrollback-down-half-page = Alt+d
scrollback-up-half-page = Alt+u
spawn-terminal = Mod4+Shift+Return

[text-bindings]
# Delete word
\x17 = Control+BackSpace 
