# Good alternative (and more bloated) themes:
# - kanagawa-dragon
# - gruvbox_material_dark_hard
# - jellybeans
# - catppuccin_mocha

### Fine for surface book
theme = "kanagawa-minimal-custom"
# theme = "kanagawa-lotus" # Until black spots on screen fixed...
# theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
scrolloff = 5
cursorline = true
rulers = [80, 100]
text-width = 88
gutters = ["diagnostics", "line-numbers", "diff"]
line-number = "relative"
true-color = true
color-modes = true
completion-timeout = 0
completion-trigger-len = 1
completion-replace = true
default-yank-register = "+"
end-of-line-diagnostics = "warning"
popup-border = "all"
continue-comments = false
trim-trailing-whitespace = true
rainbow-brackets = true


[editor.smart-tab]
supersede-menu = true

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
# To enable all: render = "all"
render.space = "none"
render.tab = "none"
render.nbsp = "all"
render.nnbsp = "all"
render.newline = "none"

[editor.whitespace.characters]
# tab = "→"
tab = " "
space = "·"
nbsp = "⍽"
nnbsp = "␣"
newline = "⏎"
# tabpad = "→ " # Render tabs as '→···'
# tabpad = ""
tabpad = ""


[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.lsp]
# Don't enable "display-inline-hints", it makes lines super long
display-messages = true
display-progress-messages = true

[editor.statusline]
separator = "·"
# NOTE: Some below (not all) have ending space included
left = [
  "mode",
  "spacer",
  "diagnostics",
  "separator",
  "workspace-diagnostics",
  "spinner",
]
center = [
  # "version-control",
  # "spacer",
  # "separator",
  "file-base-name",
  "file-modification-indicator",
  "read-only-indicator",
]
right = [
  "position",
  "separator",
  "spacer",
  "position-percentage",
  "spacer",
  "separator",
  "total-line-numbers",
]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

##################################################
# Keybindings
##################################################
### Normal mode
[keys.normal]
X = ["extend_to_line_bounds", "select_line_below"]
A-x = ["extend_to_line_bounds", "select_line_above"]
g.k = ":buffer-close"
g.o = ":buffer-close-others"
ret = "goto_word"
# Smart-tab stuff
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
# Shortcuts for surround operations:
m.w.s = "@miwms"
M = "@;mim"
A-m = "@;mam"
# Split line at cursor
C-ret = ["insert_newline", "move_char_left"]
"C-," = "@<esc>A;<ret><esc>"
pagedown = "page_cursor_half_down"
pageup = "page_cursor_half_up"
"C-'" = "@o```<ret><down>``<up><backspace>"
A-e = "move_prev_long_word_end"


[keys.normal.space]
w.w = ":write"
w.q = ":write-quit"
q.q = ":quit"
# Duplicate line, and comment original
x = "@x\"yy\"ypk<C-c>jgh"
# [I]nsert [H]eader
i.h = "@Ox<esc><C-c>hdhdxyppghy49pghkk49pghjA<space>"
# F = "file_picker"
# f = "file_picker_in_current_directory"
t = ":tree-sitter-highlight-name"
l = ":config-reload"
y = ":yank-diagnostic"
"." = "repeat_last_motion"


# S[n]ippets
[keys.normal.space.n]
"'" = "@o```<ret><down>``<up><backspace><backspace><esc>"


### Visual mode
[keys.select]
x = "select_line_below"
A-x = "select_line_above"
A-e = "move_prev_long_word_end"
# Replace 'goto' with 'extend' in visual mode, to easily select start-end
g.e = "extend_to_file_end"

## Insert mode
[keys.insert]
C-tab = "@<esc>A;<ret>"
C-ret = "open_below"


A-space = "@ <esc>hi"
C-space = "completion"
tab = "smart_tab"
C-q = "@```<ret><down>``<up><backspace>"
C-k = "@<esc>o```<ret><down>``<up><backspace>"
