# Good alternative (and more bloated) themes:
# - kanagawa-dragon
# - gruvbox_material_dark_hard
# - jellybeans
# - catppuccin_mocha
theme = "minimal-custom"

[editor]
bufferline = "multiple"
scrolloff = 5
cursorline = true
rulers = [80, 100]
text-width = 88
gutters = ["diagnostics", "line-numbers", "diff"]
line-number = "relative"
true-color = true
color-modes = true
completion-timeout = 0
completion-trigger-len = 1
completion-replace = true
default-yank-register = "+"
end-of-line-diagnostics = "warning"
popup-border = "all"
continue-comments = false
clipboard-provider = "wayland"
trim-trailing-whitespace = true

[editor.smart-tab]
supersede-menu = true

[editor.indent-guides]
character = "▏"
render = true
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
# To enable all: render = "all"
render.space = "none"
render.tab = "all"
render.nbsp = "all"
render.nnbsp = "all"
render.newline = "none"

[editor.whitespace.characters]
tab = "→"
space = "·"
nbsp = "⍽"
nnbsp = "␣"
newline = "⏎"
tabpad = "·"  # Render tabs as '→···'


[editor.soft-wrap]
enable = true
wrap-at-text-width = true

[editor.lsp]
# Don't enable "display-inline-hints", it makes lines super long
display-messages = true
display-progress-messages = true

[editor.statusline]
separator = "·"
# NOTE: Some below (not all) have ending space included
left = [
  "mode",
  "spacer",
  "diagnostics",
  "separator",
  "workspace-diagnostics",
  "spinner",
]
center = [
  "version-control",
  "spacer",
  "separator",
  "file-name",
  "file-modification-indicator",
  "read-only-indicator",
]
right = [
  "position-percentage",
  "spacer",
  "separator",
  "position",
  "separator",
  "total-line-numbers",
]

[editor.statusline.mode]
normal = "NORMAL"
insert = "INSERT"
select = "SELECT"

##################################################
# Keybindings
##################################################
### Normal mode
[keys.normal]
X = ["extend_to_line_bounds", "select_line_below"]
A-x = ["extend_to_line_bounds", "select_line_above"]
g.k = ":buffer-close"
g.o = ":buffer-close-others"
ret = "goto_word"
# Smart-tab stuff
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"
# Shortcuts for surround operations:
m.w.s = "@miwms"
M = "@;mim"
A-m = "@;mam"
# Split line at cursor
C-ret = ["insert_newline", "move_char_left"]


[keys.normal.space]
w.w = ":write"
w.q = ":write-quit"
q.q = ":quit"
# Duplicate line, and comment original
x = "@x\"yy\"ypk<C-c>jgh"
# [I]nsert [H]eader
i.h = "@Ox<esc><C-c>hdhdxyppghy49pghkk49pghjA<space>"


# S[n]ippets
[keys.normal.space.n]
c = "@O<esc>jghlki#[derive(Component<esc>"
d = "@O<esc>jghlki#[derive("
b = "@O<esc>jghlki#[derive(Bundle<esc>"
r = "@O<esc>jghlki#[require("

### Visual mode
[keys.select]
x = "select_line_below"
A-x = "select_line_above"

## Insert mode
[keys.insert]
C-ret = "open_below"
C-t = "@<esc>A;<ret>"
A-space = "@ <esc>hi"
C-space = "completion"
tab = ["commit_undo_checkpoint", "smart_tab"]
C-o = "jump_backward"
C-i = "jump_forward"
