# add it to your ~/.config/helix/languages.toml

[language-server.fsharp-ls]
command = "fsautocomplete"
args = ["--verbose"]
config = { AutomaticWorkspaceInit = true, FSharp = { ExternalAutocomplete = true } }

[[language]]
name = "fsharp"
scope = "source.fs"
roots = ["fsproj", "sln", ".git"]
file-types = ["fs", "fsx", "fsi"]
language-servers = ["fsharp-ls"]
comment-token = "//"
indent = { tab-width = 4, unit = " " }
auto-format = true

[[language]]
name = "kanata"
scope = "source.kanata"
file-types = ["kbd"]
comment-tokens = [";;"]
block-comment-tokens = [{ start = "#|", end = "|#" }]

# [[language]]
# name = "haskell"
# auto-format = true
# roots = ["Setup.hs", "stack.yaml", "cabal.project", "src/"]

[[language]]
name = "haskell"
scope = "source.haskell"
injection-regex = "hs|haskell"
file-types = ["hs", "hs-boot", "hsc"]
roots = ["Setup.hs", "stack.yaml", "cabal.project", "hie.yaml", "src/"]
shebangs = ["runhaskell", "stack"]
comment-token = "--"
block-comment-tokens = { start = "{-", end = "-}" }
language-servers = ["haskell-language-server"]
indent = { tab-width = 2, unit = "  " }
# NOTE: Enable when figured out how to prevent stalling...
auto-format = true

[language-server.haskell-language-server.config]
haskell.formattingProvider = "fourmolu"
haskell.sessionLoading = "multipleComponents"

[[language]]
name = "cabal"
auto-format = true
roots = ["*.cabal", ".cabal", "Setup.hs", "stack.yaml", "cabal.project"]

# [[language]]
# name = "ini"
# # scope = "source.ini"
# file-types = [
#   "ini",
#   "desktop",
#   { glob = "mimeapps.list" },
#   # Podman quadlets
#   "container",
#   "volume",
#   "kube",
#   "network",
#   { glob = ".editorconfig" },
#   { glob = ".npmrc" },
#   { glob = "hgrc" },
#   { glob = "npmrc" },
#   { glob = "rclone.conf" },
#   "properties",
#   "cfg",
#   "directory",
#   { glob = "config" },
# ]
# injection-regex = "ini"
# comment-token = "#"
# indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "kdl"
# auto-format = true

[[language]]
name = "nix"
auto-format = true
text-width = 80
formatter.command = "nixfmt"
formatter.args = ["--width=77", "--strict", "--verify"]


[language.auto-pairs]
'(' = ")"
'{' = "}"
'[' = "]"
'"' = '"'
'=' = ";"

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"] # Taplo not working so good

[[language]]
name = "c-sharp"
formatter = { command = "csharpier", args = ["format"] }
auto-format = true

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c"]                                  # TODO: ["h"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["clangd"]
indent = { tab-width = 2, unit = "  " }
auto-format = true


[language.auto-pairs]
'(' = ")"
'{' = "}"
'[' = "]"
'"' = '"'
"'" = "'"


[[language]]
name = "nim"
formatter = { command = "nph", args = ["-"] }
auto-format = true


[[language]]
name = "lua"
auto-format = true

[[language]]
name = "bash"
# Copied from offical
file-types = [
  { glob = "dot-zshenv" },
  { glob = "dot-zshrc" },
  "sh",
  "bash",
  "ash",
  "dash",
  "ksh",
  "mksh",
  "zsh",
  "zshenv",
  "zlogin",
  "zlogout",
  "zprofile",
  "zshrc",
  "eclass",
  "ebuild",
  "bazelrc",
  "Renviron",
  "zsh-theme",
  "cshrc",
  "tcshrc",
  "bashrc_Apple_Terminal",
  "zshrc_Apple_Terminal",
  { glob = "i3/config" },
  { glob = "sway/config" },
  { glob = "tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_login" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
  { glob = ".zlogin" },
  { glob = ".zlogout" },
  { glob = ".zprofile" },
  { glob = ".zshrc" },
  { glob = ".zimrc" },
  { glob = "APKBUILD" },
  { glob = ".bash_aliases" },
  { glob = ".Renviron" },
  { glob = ".xprofile" },
  { glob = ".xsession" },
  { glob = ".xsessionrc" },
  { glob = ".yashrc" },
  { glob = ".yash_profile" },
  { glob = ".hushlogin" },
]

[[language]]
name = "rust"
# text-width = 80
language-servers = ["snippets-ls", "rust-analyzer"]

[language.auto-pairs]
'(' = ")"
'{' = "}"
'[' = "]"
'"' = '"'
# '<' = ">"

[[grammar]]
name = "kanata"
source = { git = "https://github.com/postsolar/tree-sitter-kanata/", rev = "master" }

# [[grammar]]
# name = "typst"
# source.git = "https://github.com/uben0/tree-sitter-typst"
# source.rev = "master"

[[language]]
# name = "typst"
# auto-format = true
# formatter = ["typstyle"]
# roots = ["main.typ", "report.typ", "tinymist.lock", "out/"]
# language-servers = ["tinymist"]
### Defaults, as of 02/11-2025
name = "typst"
scope = "source.typst"
injection-regex = "typ(st)?"
file-types = ["typst", "typ"]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
language-servers = ["tinymist"]
indent = { tab-width = 2, unit = "  " }

### Mine
auto-format = true
formatter = ["typstyle"]
roots = ["main.typ", "out/", "tinymist.lock"]
[language.auto-pairs]
'"' = '"'
'`' = '`'
'(' = ')'
'{' = '}'
'[' = ']'
'$' = '$'

[language-server.tinymist]
command = "tinymist"
# args = ["lsp"]

[language-server.tinymist.config]
formatterMode = "typstyle"
exportPdf = "onType"
outputPath = "$root/out/$name"
preview.background.enabled = true
formatterPrintWidth = 80
lint.enabled = true
lint.when = "onType"
projectResolution = "lockDatabase"
# projectResolution = "singleFile"
# typstExtraArgs = ["main.typ"]

# Need both commands, evnen though top one is default
preview.background.args = [
  "--data-plane-host=127.0.0.1:23635",
  "--invert-colors=never",
]
typingContinueCommentsOnNewLine = false

[language-server.snippets-ls]
command = "snippets-ls"
args = ["-config", "home/angryluck/.config/helix/snippets/rust.json"]


[[language]]
name = "elm"
language-servers = ["elm-language-server"]

[language-server.elm-language-server]
command = "elm-language-server"
args = ["--stdio"]

[[lanuguage]]
name = "nushell"
formatter.command = "nufmt"
formatter.args = ["-s"]
auto-format = false         # Very unstable program (allegedly), careful!


[[language]]
name = "hyprlang"
scope = "source.hyprlang"
roots = ["hyprland.conf"]
file-types = [{ glob = "hypr/*.conf" }, { glob = "mango/**/*.conf" }]
comment-token = "#"
grammar = "hyprlang"
language-servers = ["hyprls"]


# Base copied from upstream, so more configs can be added
[[language]]
name = "ini"
scope = "source.ini"
file-types = [
  "ini",
  "desktop",
  { glob = "mimeapps.list" },
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  { glob = ".editorconfig" },
  { glob = ".npmrc" },
  { glob = "hgrc" },
  { glob = "npmrc" },
  { glob = "rclone.conf" },
  { glob = ".aws/config" },
  "properties",
  "cfg",
  "directory",
  { glob = ".wslconfig" },
]
injection-regex = "ini"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }


[[language]]
name = "python"
scope = "source.python"
injection-regex = "py(thon)?"
file-types = [
  "py",
  "pyi",
  "py3",
  "pyw",
  "ptl",
  "rpy",
  "cpy",
  "ipy",
  "pyt",
  { glob = ".python_history" },
  { glob = ".pythonstartup" },
  { glob = ".pythonrc" },
  { glob = "*SConstruct" },
  { glob = "*SConscript" },
  { glob = "*sconstruct" },
]
shebangs = ["python", "uv"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["ty", "ruff", "jedi", "pylsp"] #disable ty
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }
auto-format = true

# [language-server.ty.config]
# interpreter = ["$PYTHONPATH"]
[language-server.nil.config]
nix.flake.autoArchive = true
nix.flake.autEvalInputs = true

[[language]]
name = "perl"
scope = "source.perl"
file-types = [
  # "pl", # disable pl, so it doesn't interfere with prolog
  "pm",
  "t",
  "psgi",
  "raku",
  "rakumod",
  "rakutest",
  "rakudoc",
  "nqp",
  "p6",
  "pl6",
  "pm6",
  { glob = "latexmkrc" },
  { glob = ".latexmkrc" },
]
shebangs = ["perl"]
comment-token = "#"
language-servers = ["perlnavigator"]
indent = { tab-width = 2, unit = "  " }
