# Modified colors from Kanagawa Wave
# Source https//github.com/rebelot/kanagawa.nvim

[colors]
background = '#1f1f28'
foreground = '#dcd7ba'

ansi = [
  '#090618',
  '#C34043',
  '#98BB6C',
  '#E6C384',
  '#A3D4D5',
  '#B8B4D0',
  '#7E9CD8', # not cyan, just crystalBlue, lul
  '#c8c093',
]


brights = [
  '#727169',
  '#e82424',
  '#98bb6c',
  '#e6c384',
  '#7fb4ca',
  '#938aa9',
  '#7aa89f',
  '#dcd7ba',
]

selection_bg = '#2d4f67'
selection_fg = '#c8c093'

[colors.indexed]
16 = '#ffa066'
17 = '#ff5d62'
