[window]
padding = { x = 5, y = 5 }
decorations = "none"

[font]
size = 12

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u0017"  # C-w

[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "PageUp"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "PageDown"
action = "ScrollHalfPageDown"
