### Base taken from helix-repo ayu-dark/evole
# Author: André Sá <enkodr@outlook.com>
# Based on the AYU theme colors from https://github.com/dempfi/ayu

# Syntax
keyword = { fg = "light_gray", modifiers = ["bold"] }
# For @import in zig (???)
"keyword.control" = "yellow"
"type" = "cyan"
"constant.numeric" = "magenta"
"string" = "green"
"string.regexp" = "orange"
"string.special" = "orange"
"comment" = { fg = "magenta", modifiers = ["italic"] }
# "variable" = "foreground"
"label" = "orange"
"punctuation" = "gray"
# "keyword" = "orange"
# "keyword.control" = "yellow"
"keyword.directive" = "yellow"
"operator" = "orange"
"function" = "yellow"
# "tag" = "blue"
"namespace" = "blue"

# Markdown(/up)
"markup.heading" = "orange"
"markup.list" = "yellow"
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "orange", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.raw.block" = "green"
"markup.link.url" = "blue"
"markup.link.text" = "yellow"
"markup.link.label" = "green"
"markup.quote" = "yellow"

# Git
"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "yellow"

# Gutters and editing area
"error" = "red"
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"warning" = "vibrant_orange"
"diagnostic.warning" = { underline = { color = "vibrant_orange", style = "curl" } }
"hint" = "green"
"diagnostic.hint" = { underline = { color = "vibrant_yellow", style = "curl" } }
"info" = "magenta"
"diagnostic.info" = { underline = { color = "white", style = "curl" } }

# "markup.raw.block" = { bg = "black" }
"markup.raw.inline" = { bg = "black" }

"ui.cursor" = { fg = "dark_gray", bg = "light_gray" }
"ui.cursor.primary" = { fg = "dark_gray", bg = "orange" }
"ui.cursor.primary.select" = { fg = "dark_gray", bg = "magenta" }
"ui.cursor.primary.insert" = { fg = "dark_gray", bg = "green" }
"ui.text.inactive" = "gray"
"ui.bufferline" = { fg = "light_gray", bg = "background" }
"ui.bufferline.active" = { fg = "light_gray", bg = "dark_gray" }
"ui.virtual.jump-label" = { fg = "red", modifiers = ["italic", "bold"] }


# Interface
"ui.background" = { bg = "background" }
# "ui.cursor" = { fg = "dark_gray", bg = "yellow" }
# "ui.cursor.primary" = { fg = "dark_gray", bg = "orange" }
"ui.cursor.match" = "orange"
"ui.linenr" = "dark_gray"
"ui.linenr.selected" = "gray"
"ui.statusline" = { fg = "foreground", bg = "black" }
"ui.statusline.normal" = { fg = "black", bg = "blue" }
"ui.statusline.insert" = { fg = "black", bg = "orange" }
"ui.statusline.select" = { fg = "black", bg = "magenta" }
"ui.cursorline" = { bg = "black" }
"ui.popup" = { fg = "#7B91b3", bg = "black" }
"ui.window" = "dark_gray"
"ui.help" = { fg = "#7B91b3", bg = "black" }
"ui.text" = "foreground"
"ui.text.focus" = { bg = "dark_gray", fg = "foreground" }
"ui.text.info" = "foreground"
"ui.virtual.whitespace" = "dark_gray"
"ui.virtual.ruler" = { bg = "black" }
"ui.virtual.inlay-hint" = { fg = "#e6b450", bg = "#302a20" } # original bg #e6b45033
"ui.menu" = { fg = "foreground", bg = "black" }
"ui.menu.selected" = { bg = "gray", fg = "background" }
"ui.selection" = { bg = "dark_gray" }
# "warning" = "yellow"
# "error" = { fg = "red", modifiers = ["bold"] }
# "info" = { fg = "blue", modifiers = ["bold"] }
# "hint" = { fg = "blue", modifiers = ["bold"] }
# "diagnostic.hint" = { underline = { color = "blue", style = "curl" } }
# "diagnostic.info" = { underline = { color = "blue", style = "curl" } }
# "diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
# "diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
# "ui.bufferline" = { fg = "gray", bg = "background" }
# "ui.bufferline.active" = { fg = "foreground", bg = "dark_gray" }
"ui.debug" = { fg = "orange", bg = "background" }
"ui.highlight.frameline" = { bg = "#0067a3" }
# "ui.virtual.jump-label" = { fg = "red", modifiers = ["italic", "bold"] }

"special" = "orange"

[palette]
# background = "#0f1419"
foreground = "#bfbdb6"

# black = "#131721"
blue = "#59c2ff"
dark_gray = "#2d3640"
cyan = "#73b8ff"
gray = "#5c6773"
green = "#aad94c"
magenta = "#d2a6ff"
orange = "#ff8f40"
yellow = "#e6b450"
red = "#DD3E25"

background = '#020202'
black = "#0D0D0D"
light_gray = "#dedede"
vibrant_yellow = "#CFCA0D"
vibrant_orange = "#FF8732"
